apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: cicdpipeline-bank-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
  namespace: bank
spec:
  selector:
    app: bank-api
  ports:
    - port: 9090
      targetPort: 9090